### ISSUE TITLE
Namespace change when upgrading from Ibexa 3.3 to Ibexa 4.x

### ISSUE THREAD

**Issue by fsoedjede** [ibexa/fieldtype-richtext#63]
Hello,

I'm doing an upgrade from ezplatform 2.5 to Ibexa/oss 4.3
I'm facing an issue: as the namespace changed, I'm having issues with my database content.

Previously I had in the table `ezcontentobject_attribute` :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<section xmlns="http://docbook.org/ns/docbook"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml"
         xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom"
         version="5.0-variant ezpublish-1.0">
  <eztemplate name="richcontent" ezxhtml:class="ez-custom-tag ez-custom-tag--content-visible">
    <ezcontent>
      <para>Lorem ipsum ...</para>
    </ezcontent>
  </eztemplate>
</section>
```

That content produces a xml parsing error now.
If I change references from `ez.no` to `ibexa.co`, it works.

The new content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<section xmlns="http://docbook.org/ns/docbook"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:ezxhtml="http://ibexa.co/xmlns/dxp/docbook/xhtml"
         xmlns:ezcustom="http://ibexa.co/xmlns/dxp/docbook/custom"
         version="5.0-variant ezpublish-1.0">
  <eztemplate name="richcontent" ezxhtml:class="ez-custom-tag ez-custom-tag--content-visible">
    <ezcontent>
      <para>Lorem ipsum...</para>
    </ezcontent>
  </eztemplate>
</section>
```

I search in the documentation, this repository but I did not found a command which does the database migration.
In this commit https://github.com/ibexa/fieldtype-richtext/commit/acdda101bb4a05425dbe016cc2a1a8764da5868e which does renaming from `ez.no` to `ibexa.co`, I did not see anything concerning the database change.

Does an command exists?
How can I make sure the database is up to date?

Thanks

_Please excuse me if the answer is easy, i'm new in Ibexa / EzPlatform world._

**Comment by adamwojs** [comment]
Thank you for issue report, however Github Issues is not a right place to do so. Please report you bug via support.ibexa.co if you have are Ibexa customer or alternatively via issues.ibexa.co.
